# Generated by Django 4.1.1 on 2022-11-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='actorid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directors',
            name='directorid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movieid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
